CREATE TABLE IF NOT EXISTS auditoria (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    acao VARCHAR(255) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    status_code INTEGER NOT NULL,
    data_cadastro TIMESTAMP WITHOUT TIME ZONE NOT NULL
);